name = "password-locker"
type = "javascript"
zone_id = ""
account_id = "d6252a570c309c113744c9e11317e271"
route = ""
workers_dev = true
kv_namespaces = [
  { binding = "ASSETS", id = "532e8bdff5e04372abeb493c26df8a97", preview_id = "edf5d5553f464306be81dfec1354bd8c" },
  { binding = "STORAGE", id = "8c162d07bbba4f5eac941acac5742533", preview_id = "ad5996e9223c4d32abff8cbcceffc0a5" }
]

[site]
bucket = "./dist/assets"
entry-point = "."

[build]
command = "yarn build"

[build.upload]
format = "service-worker"
